source "https://rubygems.org"

ruby ">= 4.0.0"

gem "sinatra", ">= 4.0"
gem "puma", ">= 7.0"
gem "rack", ">= 3.0"
gem "ruby_llm", ">= 1.0"
gem "json", ">= 2.0"

group :development, :test do
  gem "rack-test", ">= 2.0"
  gem "rspec", ">= 3.0"
end
